'use strict';

/**
 * Pre-build script: embeds the current-platform native binaries into
 * src/embedded-natives.js so that `bun build --compile` bakes them into
 * the executable.
 *
 * One binary is embedded:
 *
 *  systray – the Go binary that the systray npm package spawns as a
 *            child process (Windows only at runtime, but we embed it
 *            during every build so the binary is self-contained)
 *
 * At runtime, native-loader.js extracts these to a per-user cache dir
 * and redirects the native module loading to the extracted paths.
 */

const fs   = require('fs');
const path = require('path');

const root    = path.join(__dirname, '..');
const outFile = path.join(root, 'src', 'embedded-natives.js');

const platform = process.platform;

// ── systray (Go binary) ──────────────────────────────────────────────────────

const systrayPkg  = require(path.join(root, 'node_modules', 'systray', 'package.json'));
const trayBinName = {
  win32:  `tray_windows_release.exe`,
  darwin: `tray_darwin_release`,
  linux:  `tray_linux_release`,
}[platform];

if (!trayBinName) {
  console.error(`[embed-natives] WARNING: unsupported platform for systray: ${platform}`);
}

const trayBinPath = trayBinName
  ? path.join(root, 'node_modules', 'systray', 'traybin', trayBinName)
  : null;

let trayContent = null;
if (trayBinPath && fs.existsSync(trayBinPath)) {
  trayContent = fs.readFileSync(trayBinPath).toString('base64');
} else if (trayBinPath) {
  console.warn(`[embed-natives] WARNING: systray binary not found at ${trayBinPath}`);
}

// ── write output ─────────────────────────────────────────────────────────────

const output = `'use strict';
// Auto-generated by scripts/embed-natives.js — do not edit manually.
// Regenerated automatically when you run: bun run build
module.exports = {
  systray: ${trayContent ? `{
    filename: ${JSON.stringify(trayBinName)},
    version:  ${JSON.stringify(systrayPkg.version)},
    content:  Buffer.from(${JSON.stringify(trayContent)}, 'base64'),
  }` : 'null'},
};
`;

fs.writeFileSync(outFile, output);

const trayKB = trayBinPath && fs.existsSync(trayBinPath)
  ? Math.round(fs.statSync(trayBinPath).size / 1024)
  : 0;
if (trayContent) {
  console.log(`[embed-natives] systray: ${trayBinName} v${systrayPkg.version} (${trayKB} KB)`);
}
