'use strict';

/**
 * Pre-build script: embeds the current-platform native binaries into
 * src/embedded-natives.js so that `bun build --compile` bakes them into
 * the executable.
 *
 * Two binaries are embedded:
 *
 *  midi   – the @julusian/midi N-API .node addon used by easymidi
 *           (pkg-prebuilds picks the right file for the current platform)
 *
 *  systray – the Go binary that the systray npm package spawns as a
 *            child process (Windows only at runtime, but we embed it
 *            during every build so the binary is self-contained)
 *
 * At runtime, native-loader.js extracts these to a per-user cache dir
 * and redirects the native module loading to the extracted paths.
 */

const fs   = require('fs');
const path = require('path');
const os   = require('os');

const root    = path.join(__dirname, '..');
const outFile = path.join(root, 'src', 'embedded-natives.js');

// ── midi (.node addon) ──────────────────────────────────────────────────────

const { getPrebuildName, isAlpine } = require(
  path.join(root, 'node_modules', 'pkg-prebuilds', 'lib', 'prebuild')
);
const midiOptions = require(
  path.join(root, 'node_modules', '@julusian', 'midi', 'binding-options')
);
const midiBase = path.join(root, 'node_modules', '@julusian', 'midi');

const arch     = os.arch();
const platform = os.platform();
const libc     = (platform === 'linux' && isAlpine(platform)) ? 'musl' : undefined;

const napi = midiOptions.napi_versions[0];
const prebuildName = getPrebuildName({
  name: midiOptions.name, platform, arch, libc, napi_version: napi, runtime: 'node',
});
const midiNodePath = path.join(midiBase, 'prebuilds', prebuildName);

if (!fs.existsSync(midiNodePath)) {
  console.error(`[embed-natives] ERROR: midi .node not found at ${midiNodePath}`);
  console.error('Run `bun install` first, then retry the build.');
  process.exit(1);
}

const midiContent  = fs.readFileSync(midiNodePath).toString('base64');
const midiFilename = path.basename(midiNodePath); // e.g. "node-napi-v7.node"

// ── systray (Go binary) ──────────────────────────────────────────────────────

const systrayPkg  = require(path.join(root, 'node_modules', 'systray', 'package.json'));
const trayBinName = {
  win32:  `tray_windows_release.exe`,
  darwin: `tray_darwin_release`,
  linux:  `tray_linux_release`,
}[platform];

if (!trayBinName) {
  console.error(`[embed-natives] WARNING: unsupported platform for systray: ${platform}`);
  // Continue — systray is Windows-only at runtime anyway; we still embed a
  // dummy entry so the generated file has a consistent shape.
}

const trayBinPath = trayBinName
  ? path.join(root, 'node_modules', 'systray', 'traybin', trayBinName)
  : null;

let trayContent = null;
if (trayBinPath && fs.existsSync(trayBinPath)) {
  trayContent = fs.readFileSync(trayBinPath).toString('base64');
} else if (trayBinPath) {
  console.warn(`[embed-natives] WARNING: systray binary not found at ${trayBinPath}`);
}

// ── write output ─────────────────────────────────────────────────────────────

const output = `'use strict';
// Auto-generated by scripts/embed-natives.js — do not edit manually.
// Regenerated automatically when you run: bun run build
module.exports = {
  midi: {
    filename: ${JSON.stringify(midiFilename)},
    content: Buffer.from(${JSON.stringify(midiContent)}, 'base64'),
  },
  systray: ${trayContent ? `{
    filename: ${JSON.stringify(trayBinName)},
    version:  ${JSON.stringify(systrayPkg.version)},
    content:  Buffer.from(${JSON.stringify(trayContent)}, 'base64'),
  }` : 'null'},
};
`;

fs.writeFileSync(outFile, output);

const midiKB   = Math.round(fs.statSync(midiNodePath).size / 1024);
const trayKB   = trayBinPath && fs.existsSync(trayBinPath)
  ? Math.round(fs.statSync(trayBinPath).size / 1024)
  : 0;
console.log(`[embed-natives] midi: ${midiFilename} (${midiKB} KB)`);
if (trayContent) {
  console.log(`[embed-natives] systray: ${trayBinName} v${systrayPkg.version} (${trayKB} KB)`);
}
