'use strict';

/**
 * Pre-build script: reads every file from public/ and writes
 * src/embedded-public.js, a CommonJS module that exports them
 * as Buffers with their MIME types.
 *
 * This lets `bun build --compile` bake the UI assets into the binary so
 * no separate public/ directory needs to be shipped.
 */

const fs   = require('fs');
const path = require('path');

const publicDir = path.join(__dirname, '..', 'public');
const outFile   = path.join(__dirname, '..', 'src', 'embedded-public.js');

const MIME_TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.js':   'application/javascript; charset=utf-8',
  '.css':  'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.png':  'image/png',
  '.jpg':  'image/jpeg',
  '.svg':  'image/svg+xml',
  '.ico':  'image/x-icon',
};

function collectFiles(dir, base) {
  const entries = [];
  for (const name of fs.readdirSync(dir)) {
    const abs = path.join(dir, name);
    const rel = base + '/' + name;
    if (fs.statSync(abs).isDirectory()) {
      entries.push(...collectFiles(abs, rel));
    } else {
      entries.push({ abs, rel });
    }
  }
  return entries;
}

const files = collectFiles(publicDir, '');

const lines = files.map(({ abs, rel }) => {
  const content  = fs.readFileSync(abs).toString('base64');
  const mimeType = MIME_TYPES[path.extname(rel)] || 'application/octet-stream';
  return (
    `  ${JSON.stringify(rel)}: ` +
    `{ content: Buffer.from(${JSON.stringify(content)}, 'base64'), ` +
    `mimeType: ${JSON.stringify(mimeType)} }`
  );
});

const output = `'use strict';
// Auto-generated by scripts/embed-public.js — do not edit manually.
// Regenerated automatically when you run: bun run build
module.exports = {
${lines.join(',\n')},
};
`;

fs.writeFileSync(outFile, output);
console.log(`[embed-public] Embedded ${files.length} file(s): ${files.map(f => f.rel).join(', ')}`);
